// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnb039fF31DWmCaHhmM54sFwoc9fkAb6w',
    appId: '1:1003756518346:web:775764880fa698e6daad33',
    messagingSenderId: '1003756518346',
    projectId: 'rentapp-nafi',
    authDomain: 'rentapp-nafi.firebaseapp.com',
    storageBucket: 'rentapp-nafi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ6EF5FyGbT26LmuooEAYrzLRa-TvF-3c',
    appId: '1:1003756518346:android:493383261d2383fcdaad33',
    messagingSenderId: '1003756518346',
    projectId: 'rentapp-nafi',
    storageBucket: 'rentapp-nafi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtUfJd-X61vL1TzwnvXI6J_i4kVP3vxLw',
    appId: '1:1003756518346:ios:e300ab0d04eecde4daad33',
    messagingSenderId: '1003756518346',
    projectId: 'rentapp-nafi',
    storageBucket: 'rentapp-nafi.firebasestorage.app',
    iosBundleId: 'com.carrental.carRentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtUfJd-X61vL1TzwnvXI6J_i4kVP3vxLw',
    appId: '1:1003756518346:ios:e300ab0d04eecde4daad33',
    messagingSenderId: '1003756518346',
    projectId: 'rentapp-nafi',
    storageBucket: 'rentapp-nafi.firebasestorage.app',
    iosBundleId: 'com.carrental.carRentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnb039fF31DWmCaHhmM54sFwoc9fkAb6w',
    appId: '1:1003756518346:web:00f11fa5ad7dc150daad33',
    messagingSenderId: '1003756518346',
    projectId: 'rentapp-nafi',
    authDomain: 'rentapp-nafi.firebaseapp.com',
    storageBucket: 'rentapp-nafi.firebasestorage.app',
  );
}
